/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/a9zBoUZEU0I
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  SheetTrigger,
  SheetClose,
  SheetContent,
  Sheet,
} from "@/components/ui/sheet";
import { JSX, SVGProps } from "react";

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";

export function Navbar() {
  const menus = [
    { name: "Home", href: "/" },
    { name: "About", href: "/test" },
    { name: "Portfolio", href: "#" },
    { name: "Blog", href: "/blog" },
    { name: "Contact", href: "#" },
  ];

  return (
    <header className="fixed top-0 z-50 flex h-16 w-full items-center justify-between bg-white px-4 shadow-sm dark:bg-gray-950 md:px-6">
      <Link className="flex items-center gap-2" href="/">
        <Avatar>
          <AvatarImage src="/lijar.jpg" />
          <AvatarFallback>LJ</AvatarFallback>
        </Avatar>
        <span className="font-semibold">LI JAR</span>
      </Link>
      <nav className="hidden items-center gap-4 md:flex">
        {menus.map((menu)=>{
          return(
            <Link
            key={menu.name}
          className="text-sm font-medium text-gray-500 transition-colors hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
          href={menu.href}
        >
          {menu.name}
        </Link>
          )
        })}
        
      </nav>
      <Sheet>
        <SheetTrigger asChild>
          <Button className="md:hidden" size="icon" variant="outline">
            <MenuIcon className="h-6 w-6" />
            <span className="sr-only">Toggle navigation menu</span>
          </Button>
        </SheetTrigger>
        <SheetContent side="right">
          <div className="flex h-full flex-col justify-between p-6">
            <nav className="grid gap-4">
              {menus.map((menu)=>{
                return(
                  <SheetClose asChild key={menu.name}>
                <Link
                
                  className="text-sm font-medium text-gray-500 transition-colors hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  href={menu.href}
                >
                  {menu.name}
                </Link>
              </SheetClose>
                )
              })}
              
            </nav>
            <div className="flex items-center justify-between">
              <Link className="flex items-center gap-2" href="#">
                <Avatar>
                  <AvatarImage src="/lijar.jpg" />
                  <AvatarFallback>LJ</AvatarFallback>
                </Avatar>
                <span className="font-semibold">LI JAR</span>
              </Link>
              <SheetClose asChild>
                <Button size="icon" variant="ghost">
                  <XIcon className="h-6 w-6" />
                </Button>
              </SheetClose>
            </div>
          </div>
        </SheetContent>
      </Sheet>
    </header>
  );
}

function MenuIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function MountainIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}

function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
